from django.db import models

# Create your models here.
class Overdoses(models.Model):
    abbrev = models.TextField(max_length=2,primary_key=True)
    state = models.TextField()
    population = models.IntegerField()
    deaths = models.IntegerField()
    deaths_ppop = models.DecimalField(max_digits=7,decimal_places=2)

class Prescribers(models.Model):
    doctorid = models.TextField(primary_key=True,null=False)
    fname = models.TextField()
    lname = models.TextField()
    gender = models.TextField(max_length=1)
    state = models.TextField(max_length=2)
    credentials = models.TextField()
    multiple_degrees = models.IntegerField(null=True)
    specialty = models.TextField()
    opioid_prescriber2 = models.BooleanField()

class Prescriptions(models.Model):
    doctorid = models.TextField(primary_key=True,null=False)
    totalprescriptions = models.IntegerField()
    total_opiate_p = models.DecimalField(max_digits=7,decimal_places=6)
    total_opiate_p_value = models.DecimalField(max_digits=7,decimal_places=6)
    avg_by_speciality = models.DecimalField(max_digits=9,decimal_places=8)
    dif_by_speciality = models.DecimalField(max_digits=7,decimal_places=6)
    acetaminophen_codeine = models.DecimalField(max_digits=7,decimal_places=6)
    acetmin_p  = models.DecimalField(max_digits=7,decimal_places=6)
    avg_acetmin_p  = models.DecimalField(max_digits=7,decimal_places=6)
    dif_acetmin_p  = models.DecimalField(max_digits=7,decimal_places=6)
    fentanyl  = models.DecimalField(max_digits=7,decimal_places=6)
    fenty_p  = models.DecimalField(max_digits=7,decimal_places=6)
    avg_fenty_p  = models.DecimalField(max_digits=7,decimal_places=6)
    dif_fenty_p  = models.DecimalField(max_digits=7,decimal_places=6)
    hydrocodone_acetaminophen = models.DecimalField(max_digits=7,decimal_places=6)
    hydro_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_hydro_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_hydro_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    hydromorphone_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    hydromorphone_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_hydromorphone_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_hydromorphone_p = models.DecimalField(max_digits=7,decimal_places=6)
    methadone_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    methadone_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_methadone_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_methadone_p = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_sulfate = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_morphine_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_morphine_p = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_sulfate_er = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_ext_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_morphine_ext_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_morphine_ext_p = models.DecimalField(max_digits=7,decimal_places=6)
    oxycodone_acetaminophen = models.DecimalField(max_digits=7,decimal_places=6)
    oxy_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_oxy_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_oxy_aceta_p = models.DecimalField(max_digits=7,decimal_places=6)
    oxycodone_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    oxy_hcl_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_oxy_hcl_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_oxy_hcl_p = models.DecimalField(max_digits=7,decimal_places=6)
    oxycontin = models.DecimalField(max_digits=7,decimal_places=6)
    oxycotin_p = models.DecimalField(max_digits=7,decimal_places=6)
    avg_oxycotin_p = models.DecimalField(max_digits=7,decimal_places=6)
    dif_oxycotin_p = models.DecimalField(max_digits=7,decimal_places=6)
    tramadol_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    tramadol_p= models.DecimalField(max_digits=7,decimal_places=6)
    avg_tramadol_p= models.DecimalField(max_digits=7,decimal_places=6)
    dif_tramadol_p= models.DecimalField(max_digits=7,decimal_places=6)
  
class Prescription_Risk(models.Model):
    doctorid = models.TextField(primary_key=True,null=False)
    opioidprescriber =models.BooleanField()
    totalprescriptions = models.IntegerField()
    cephalexin = models.IntegerField()
    ciprofloxacin_hcl = models.IntegerField()
    ibuprofen = models.IntegerField()
    lyrica = models.IntegerField()
    quetiapine_fumarate = models.IntegerField()
    sumatriptan_succinate = models.IntegerField()
    zolpidem_tartrate = models.IntegerField()
    likelihood = models.DecimalField(max_digits=7,decimal_places=6)
    rating = models.TextField()

class Drug_Quant_Rec(models.Model):
    doctorid = models.TextField(primary_key=True,null=False)
    acetaminophen_codeine = models.DecimalField(max_digits=7,decimal_places=6)
    fentanyl = models.DecimalField(max_digits=7,decimal_places=6)
    hydrocodone_acetaminophen = models.DecimalField(max_digits=7,decimal_places=6)
    hydroxyzine_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    methadone_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_sulphate = models.DecimalField(max_digits=7,decimal_places=6)
    morphine_sulphate_er = models.DecimalField(max_digits=7,decimal_places=6)
    oxycodone_acetaminophen = models.DecimalField(max_digits=7,decimal_places=6)
    oxycodone_hcl = models.DecimalField(max_digits=7,decimal_places=6)
    oxycontin = models.DecimalField(max_digits=7,decimal_places=6)
    tramadol = models.DecimalField(max_digits=7,decimal_places=6)
    higher_than_avg = models.DecimalField(max_digits=7,decimal_places=6)
    lower_than_avg = models.DecimalField(max_digits=7,decimal_places=6)
    presc_less = models.TextField()
    presc_more = models.TextField()

class High_Presc(models.Model):
    doctorid = models.TextField(primary_key=True,null=False)
    acetmin_high = models.IntegerField()
    fenty_high = models.IntegerField()
    hydro_aceta_high = models.IntegerField()
    hydromorphone_high = models.IntegerField()
    methadone_high = models.IntegerField()
    morphine_high = models.IntegerField()
    morphine_ext_high = models.IntegerField()
    oxy_aceta_high = models.IntegerField()
    oxy_hcl_high  = models.IntegerField()
    oxycotin_high = models.IntegerField()
    tramadol_high = models.IntegerField()


class Opiods_Related(models.Model):
    id = models.IntegerField(primary_key=True)
    drugName = models.TextField(null=False)
    isOpioid = models.BooleanField()
    OverPresc = models.DecimalField(max_digits=7,decimal_places=6)
    name_link = models.TextField()