# Generated by Django 2.1.5 on 2019-04-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opiods_Related',
        ),
    ]
