# Generated by Django 2.1.5 on 2019-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_opiods_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiods_Related',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('drugName', models.TextField()),
                ('isOpioid', models.BooleanField()),
                ('OverPresc', models.DecimalField(decimal_places=6, max_digits=7)),
                ('name_link', models.TextField()),
            ],
        ),
    ]
