# Generated by Django 2.1.5 on 2019-04-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_opiods_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription_risk',
            old_name='quetianpine_fumarate',
            new_name='quetiapine_fumarate',
        ),
    ]
